### ISSUE TITLE
Dog Controller Rspec Test

### ISSUE THREAD

**Issue by docvego** [ophrescue/RescueRails#363]
Dog Controller Rspec Test

**Comment by TheDudeWithTheThing** [comment]
branch here if you want to keep see what I'm doing, will try to push often and squash so it makes sense, I think once I'm done with tests, for index anyway, I'm going to make a DogSearcher service object because all that logic in the controller gives me the heebie jeebies

https://github.com/ophrescue/RescueRails/tree/dogs-controller-specs

**Comment by TheDudeWithTheThing** [comment]
yeah!
