### ISSUE TITLE
Users Staff Directory Should Support Canadian Mailing Addresses

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#437]
```/users``` lacks a Country Field Dropdown.  

@tobymurray might be a good start for you so we can properly add you to the volunteer directory! 😄

**Comment by tobymurray** [comment]
As in CRUDing the users is missing the field? Limit it to any specific countries, or pull in everything?

**Comment by markottaviani** [comment]
Yup!  

Limit to United States of America and Canada is good for now (default to US in the database migration) .  

Break out the database migration into a separate pull request, because we like to deploy those our first.  

Also, if you see any other issues with the input validation for Users Object's address field to properly support Canada, note those here and we'll try to sort them out.  Thanks!

**Comment by tobymurray** [comment]
Canada has provinces/territories instead of states (theoretically could abuse the current field), and 6 character alphanumeric postal codes instead of zip codes (oddly enough compatible with the database, but not the User model as written). So definitely a little work to do there to support it nicely. I think a localized form would be the most useful way of handling it, I'm sure it would be straightforward enough with a little JS, and there's likely one on the internet somewhere we could leverage.

It's also looking like it'd be nice to break out the addresses into a separate table, so multinational support would be free for `adopters` and `banned_adopters`. Potentially `events` as well? Not saying it should be done as part of this, but something to think about.

**Comment by tobymurray** [comment]
Fleshing out what the application layer refactoring looks like to support [name change PR](https://github.com/ophrescue/RescueRails/pull/629), I pushed a branch [here](https://github.com/ophrescue/RescueRails/compare/437-Use-more-generic-address-terms...437-Rename-application-layer-properties?expand=1). My intention is that absolutely nothing is different from the user's perspective; the API changes (I assume it only drives the UI?) and the `User` model property names change. 

From there, I was thinking:
- Add application layer support for province and non-US postal code
- Add `country` property to user
- Update `User` form to toggle between state/ZIP and province/postal code depending on which country is selected

Does this sound like it lines up with what was in mind for this ticket?
