### ISSUE TITLE
Dog Filters for Manager view

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#594]
Related to #357

Provide Advanced Filtering Options on the Dog Manager Screen

Should Provide
* Quick Identification of Dogs that need Foster Homes
* Lots of other stuff

**Comment by markottaviani** [comment]
Exploring the use of dropdown multiselects  as a UI option  

http://jsbin.com/qugefi/1/edit?html,css,output

**Comment by markottaviani** [comment]
https://cl.ly/2x3l1H282q1I


some UI progress.. not pretty but we can save that for Bootstrap upgrade time

**Comment by markottaviani** [comment]
@TheDudeWithTheThing how would you handle responding to a GET like this?

```/dogs?utf8=✓&age=young&size=medium&size=large&status=adoptable&status=adopted```

*Show me all dogs where (AGE = 'young'  AND size in ('medium','large') and status in ('adoptable', 'coming soon')  

Filtering here might wind up along a lot of different mixed and matched criteria:
* Age
* Size
* Status
* Flags (so checking if any number of booleans for that dog are set to true or false)


Scopes?  https://github.com/plataformatec/has_scope

**Comment by Elisabeth-OPH** [comment]
Not sure if commenting correctly but maybe add status for dogs i.e. instead of just coming soon have coming soon needs foster. Allow DMS dog search/filter (manager view) coming soon needs foster to easily see what dogs need fosters. When dogs are added to DMS and don't have a foster status would be coming soon needs foster. When foster is added status is changed to coming soon.
