### ISSUE TITLE
Reporting Data Analysis

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#616]
What reporting/stats should we collect and report on?

POC - Erin Fitzgerald and Marcy Lindenmuth.

**Comment by muhannadnouri** [comment]
I have experience with data analysis and visualization, I would love to be able to contribute to a "Statistics" section/page with any data that I can be given access to.

Interesting statistics and information would be:
- Adoption rate by foster parents
- Percentage of animals euthanized simply because there isn't anyone to adopt them
- Total intake per month or year (any time interval). Historical data from OPH would be very useful here
- Average age of animal at intake

**Comment by markottaviani** [comment]
@muhannadnouri   I think we'd be looking to able to provide some dynamic stats based on the data available in our database schema.    If you want to take #996 to start with I can look into the specifics reporting that would be useful to the Rescue and update this issue.  Thanks!

**Comment by muhannadnouri** [comment]
Sounds good, I'll look into #996 meanwhile you hear back from them!
