### ISSUE TITLE
Basic storefront

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#706]
Rescue is currently using Shopify, however has very low volume of transactions, and is losing money.  Rescue has requested, if possible, a basic storefront be added to the site.

**Comment by blai00** [comment]
Is there any requirements for the store? Or is it just another page where you have options to buy items from Rescue.

**Comment by markottaviani** [comment]
Not much other than something very very basic. I’ll get a contact for you
to work with.

**Comment by markottaviani** [comment]
So they're looking for a general storefront experience, at least all the key stuff from the customer side.

* Gallery of 8-10 items to buy, likely multiple sizes or types of each item
* Shopping Cart
* Online Payment (probably going through Stripe)

The bigger question at this point is if it's worth building that from scratch or trying to drop something existing in.    

@TheDudeWithTheThing any thoughts on that?

**Comment by blai00** [comment]
Would we need to pay for something existing to drop in or do we have access to some free shop? If we do build from scratch, I think it would be more worthwhile to have a full-scale custom shop vs. 8-10 items (unless I am mistaken about that part).  Jen mentioned she really liked Best Friends Animal Society store, but to me it seems excessive to what they want.

**Comment by markottaviani** [comment]
Yeah keep it simple

 Check out http://www.piggybak.org/

**Comment by blai00** [comment]
Do we want users to sign in once, the whole site will be under that user, or do we want them to sign up separately  specifically for the store? Piggbak is able to auto connect to the User model using Devise so I am curious what the best way of signing in is.

**Comment by markottaviani** [comment]
Can we avoid having customers log in at all?

**Comment by blai00** [comment]
Not with Piggybak, the gem assumes we already have a User Model that it can connect with so I am not sure if its going to change our current  model (doesn't seem like it though). Looking at their demo, you could end up checking out as a "guest" but it still needs some User Model.

**Comment by markottaviani** [comment]
Okay, if the User model just gets used for Store Admins, and customers just
check out as guests we should be good.

**Comment by blai00** [comment]
So, looking through the documentation more. Do we want a separate model like "buyer" to distinguish who owns buying items. Also, they recommend having RailsAdmin and Devise because Piggybak has a dependency for it. Just checking how to design this so I don't completely change things for the main part of the website.
![Screen Shot 2018-02-13 at 10.36.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599b2d64eec2e4001a0a8a60/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f06b7191a379ef0c2857415e48bc30254d58eeb9cb74fce36f34985619e8d53c0b70933518a8ea854ce901ba228b4fd7b4eddc1993fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae94851a3133467e277306e0a.png)
![Screen Shot 2018-02-13 at 10.33.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599b2d64eec2e4001a0a8a60/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f06b7191a379ef0c2852415e4abc30254d58eeb9cb74fce36f34985619e8d53c0b70933518a8ea854ce901ba228b4fd7b4eddc1993fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae94851a3133562e174366e0a.png)

**Comment by markottaviani** [comment]
Hmm yeah folding this in might be pretty rough. 

Splitting out the buyers might make sense just for the better seperation from the normal logged staff users.

Want to just take a shot at building out the functionality?
