### ISSUE TITLE
Dog Status Definition page returns 406 error

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#841]
`/dog-status-definitions` returns a 406 error

**Comment by lazylester** [comment]
yes, this is intentional... is there still a link somewhere. The status defs are shown as tooltips now, so a link to a standalone page is not required. But maybe it's used somewhere that I didn't notice?

**Comment by TheDudeWithTheThing** [comment]
doh, let's see if rollbar has where this thing is coming from

**Comment by markottaviani** [comment]
I really thought I got to that page from from little "i" next to the status on the public view page.

**Comment by TheDudeWithTheThing** [comment]
Referer | https://ophrescue.org/dogs/7407

**Comment by TheDudeWithTheThing** [comment]
the I is a bug now too

https://www.dropbox.com/s/yfkvh5nyhf4b00p/Screenshot%202018-07-16%2021.00.30.png

**Comment by markottaviani** [comment]
Yeah, the blue i  is a bug, see #842

I don't see the issue with that page either.  Maybe some folks had it bookmarked?  Regardless we can leave the page around for now.

**Comment by lazylester** [comment]
wouldn't it be better _not_ to (re-)introduce unused code, but instead to have a custom 406 page that "gently" informs the user that the page they are looking for is now obsolete? Otherwise we are obliged to keep unused static pages around forever (like those very many images that I moved into an archive folder under app/assets/images).

Assuming, of course, that there's not a link to this page that I've missed.

**Comment by lazylester** [comment]
I'm wondering, too, how we got a 406 error for this page. I'm seeing 404 for non-existent static pages.

**Comment by lazylester** [comment]
we should never see 406, even for pages that don't exist

**Comment by TheDudeWithTheThing** [comment]
@lazylester 406 means the endpoint is there but it can't render html, which makes sense since the html wasn't there to render, valid resource but can't show anything.

**Comment by lazylester** [comment]
@TheDudeWithTheThing I think you're describing 404. According to my research:

> (406) indicates that the server cannot produce a response matching the list of acceptable values defined in the request's proactive content negotiation headers, and that the server is unwilling to supply a default representation.

**Comment by TheDudeWithTheThing** [comment]
404 would mean the endpoint / route isn't there, but since it's routed to the pages controller it is 100% there.

our 406 is
```
client, "hey give me html"
server, "sorry, I can't give you html and I'm unwilling to supply a default representation"
```

**Comment by TheDudeWithTheThing** [comment]
I 100% agree with removing anything that is not used. Where does this tooltip show up now?  Is it related to the image I posted above?  BTW we only have 1 rollbar for this thing.

https://rollbar.com/OperationPawsforHomes/Ophrescue/items/431/?item_page=0&#instances

**Comment by lazylester** [comment]
the tooltip shows up in (e.g.) [https://ophrescue.org/dogs/7481](https://ophrescue.org/dogs/7481), where you'll see a little blue 'i' information icon at the end of the title line. At this moment, the text is 'translation missing' but PR#850 will fix that.

**Comment by lazylester** [comment]
@TheDudeWithTheThing 
I just investigated your assertion about 404/406. I added a route to the routes.rb for /foobar, but there's no file to render for that route, according to your explanation the response s/b 406. But the response is actually, correctly, 404. So I believe there's still not a satisfactory explanation for the 406.

**Comment by TheDudeWithTheThing** [comment]
one does not simply add a route to get a 406.  Here's how I reproduced.

create file `app/controllers/foobars_controller.rb`

```
class FoobarsController < ApplicationController
  def index
  end
end
```

add this to your routes.rb

```
resources :foobars
```

hit up localhost:3000/foobars for a 406

if you delete the index method from the controller now it's a 404 since that route / action is not defined

**Comment by TheDudeWithTheThing** [comment]
here's my 2nd experiment which I found interesting

1. add `static_foobars` to the `STATIC_PAGES` array
2. go to localhost:3000/static_foobar to get a 404
3. add `app/views/pages/static_foobar.html.erb` and now it works, the action `static_foobar` is magically created because there's now a template to render for the implied action.

Why is `dog-status-definitions` different?  The action is defined on pages controller to set the variable to hide the header. So we have an action defined, but no template, thus the 406, just like the foobar example above.

**Comment by lazylester** [comment]
"set the variable to hide the header" ?
Only the topbar is hidden, so no navigation elements. Everything else is present in the layout template.

**Comment by TheDudeWithTheThing** [comment]
yeah this

```
  def dog_status_definitions
    @hide_topbar = true
  end
```

Sorry was doing it from memory since I'm in a meeting.  No matter what it's doing the action is now defined on the controller regardless of existing template.
