### ISSUE TITLE
Make dog search options bar more prominent

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#849]
>  I was wondering if it is possible to get a search bar back. For adoption coordinators it’s really time consuming to have to click through the filters.  When we do litters we have to look up 6-8 dogs unfortunately the way it is currently isn’t so user friendly
-Kate Polits

**Comment by lazylester** [comment]
What search sequence is being envisioned here?

For example, if I'm searching for 6-8 dogs by name, the current UI adds just one extra click per search. Hardly "time consuming".  Can we request clarification of the sequence of searches?

**Comment by markottaviani** [comment]
I think the two things to adjust are:

1. Have a way to click back to the search results when on the
dog_manager/show page
(Which existed in the old view).

2. Move the search options out onto their own row above the filters,
similar to how it was in the old version.  The search options checkbox
(name/id/breed/microchip) can probably get turned into a select box,
defaulting to name.

**Comment by markottaviani** [comment]
Passing on a comment from a user that saw this github issue:

> To clarify his question we just want a search bar we don’t want to have to click a box to have to type something in. Before we just had a bar there ( similar to the url bar) and we just hit search. Now we have to find the drop down then click in the box. A lot of us use our phone to do things for OPH so with time it does get very time consuming.

**Comment by lazylester** [comment]
Well, I'm not the best person to comment, since it was my judgement that the styling I designed was good! And that the single extra click is a small penalty for a tidy GUI. But...

If I were going to move the search box out of the dropdown. I would still keep the existing "search" icon and "clear" icon to trigger search and clear, and are only shown when there is a search string present, styled as [bootstrap button addons](http://getbootstrap.com/docs/4.1/components/input-group/#button-addons). I feel that the persistent bright blue bootstrap search button is a regression to a noisy UI design in which everything seems to compete for primacy.

The current compact style of search box can still be kept in its current position, vs. relocated above the other filter items. To me, this seems consistent with a rational visual information hierarchy.

I would suggest, too, looking at bootstrap's [buttons with dropdowns](http://getbootstrap.com/docs/4.1/components/input-group/#buttons-with-dropdowns) for the select button, because of its compactness.

It may be that entering a comma-separated list of names into the search field would provide a quick way to search for multiple dog names in a single search. Perhaps this would be a better way to make the commenter's searches more efficient.

Any time there's a change in the UI, it takes users a little time to get used to the new interface. And some may be resistant. With all due respect to others who may disagree, I am personally happy with the current design, and I'm questioning whether we should have done a design change at all if users were happy with the previous design.

**Comment by markottaviani** [comment]
@Jngai  would you like to give this one a try?

**Comment by Jngai** [comment]
@markottaviani sure I will try it. I may have questions for you.

**Comment by kateugenio** [comment]
I'd like to take this one on.

**Comment by kateugenio** [comment]
Does this include the Cat Manager search?

**Comment by markottaviani** [comment]
Just updating the dog one is good, though the code is pretty much
identical.

**Comment by markottaviani** [comment]
thanks again!
